name: Mirror Repository

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to GitHub Mirror
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Check Secret
        run: |
          if [ -z "${{ secrets.MIRROR_TOKEN }}" ]; then
          echo "TOKEN EMPTY"
          exit 1
          else
          echo "TOKEN OK"
          fi

          git remote add mirror https://x-access-token:${{ secrets.MIRROR_TOKEN }}@github.com/dhevvlabel/daffaramdhani-porto.git

          git push mirror main --force
